### ISSUE TITLE
Calendar showing month & year correct but dates and weeks according to the previous year

### ISSUE THREAD

**Issue by azazelA** [maurovieirareis/hello-week#1]
Hi @maurovieirareis The dates are correct but the weeks arrangement looks mixed up. Can you please look into it? 
This is the side by side comparison of my mac's calendar and the online demo.
<img width="1678" alt="screen shot 2018-04-09 at 9 40 29 pm" src="https://user-images.githubusercontent.com/19649989/38510581-ec685c12-3c3e-11e8-8de3-8ab9c95f5759.png">
This is where I've implemented this
<img width="759" alt="screen shot 2018-04-09 at 9 45 47 pm" src="https://user-images.githubusercontent.com/19649989/38510835-a93f8c0c-3c3f-11e8-81bd-1da608e815a7.png">

**Comment by mauroreisvieira** [comment]
Hi @azazelA thanks for you report! :)

**Comment by azazelA** [comment]
Is there any way you can get it working for me? I've already implemented this in my template and this is the most light weight calendar I found without having to use jQuery.. I really don't wanna have to revert the changes and go look for an alternate one. The dates for 2018 are correct in the 2019 panels theres a one year difference going on somehow?

**Comment by azazelA** [comment]
@maurovieirareis what if I need to change the start date of the calendar? e.g. I want to set it for the year 2019 for when it opens the first time.

**Comment by azazelA** [comment]
@maurovieirareis I'm also not able get the selected date from weekdays. It should still allow weekdays to be selectable and work with `lastSelectedDay`. I am not sure if you made an option for it though

**Comment by mauroreisvieira** [comment]
@azazelA in this moment the calendar not permit to define the start date, but i will start work in this improvement and also fix the year bug.

**Comment by mauroreisvieira** [comment]
Hi again @azazelA the version 0.0.5 is available. 
If you have some question please talk to me.

This new version allows define the defaultDate, in this current version you need to specify all date eg: 2019/06/24.
