### ISSUE TITLE
Month Date Range

### ISSUE THREAD

**Issue by tearhear18** [maurovieirareis/hello-week#10]
When I choose month january then proceed to month march, range does not work. 
seems like range work only inside the displayed month.

**Comment by mauroreisvieira** [comment]
Hi @tearhear18, yes it's a bug.
In a few days I a go publish the version 2.0.0 an this bug is fixed.

**Comment by tearhear18** [comment]
do you have the bleeding branch i can help you to resolve it asap

**Comment by mauroreisvieira** [comment]
@tearhear18 yes. It's great.

You can Fork the repository, make the changes and create a Pull Request.

**Comment by tearhear18** [comment]
i can't push the fixtures

**Comment by tearhear18** [comment]
I added this in line 188, inside the method selectDay, inside for loop of activeDates
what it does is during init of day if interval has content and first element match the timestamp class is added to it same with second element. quick fix but can be refactored 
if (this.options.range) {
                
                if (this.interval[0]){
                    if(this.interval[0].dataset.timestamp == this.activeDates[i].dataset.timestamp){
                        this.activeDates[i].add(HelloWeek.CSS_CLASSES.IS_SELECTED);
                    }
                }
                if (this.interval[1]){
                    if(this.interval[1].dataset.timestamp == this.activeDates[i].dataset.timestamp){
                        this.activeDates[i].add(HelloWeek.CSS_CLASSES.IS_SELECTED);
                    }
                }
            }

**Comment by mauroreisvieira** [comment]
@tearhear18 thanks, I will check and updated.

**Comment by tearhear18** [comment]
<img width="578" alt="screenshot 2018-11-29 at 8 29 34 pm" src="https://user-images.githubusercontent.com/4946755/49221962-8ce35780-f415-11e8-8df7-a28519da616a.png">
<img width="569" alt="screenshot 2018-11-29 at 8 29 47 pm" src="https://user-images.githubusercontent.com/4946755/49221963-8d7bee00-f415-11e8-9817-c4a7732ac53e.png">
fix tested and working

**Comment by mauroreisvieira** [comment]
Yes, but a see another problem, in array with selected days. But today I launch a version with this problems solved.  

Thanks.

p.s: Nice look in calendar.

**Comment by tearhear18** [comment]
in my version i added selected_days_member class, if first element of interval is greater and last element is less than target elm

**Comment by tearhear18** [comment]
about the selected days array, logic can be calculated between start and end date, how ever would be better to have it too :D

**Comment by mauroreisvieira** [comment]
@tearhear18 you have been doing some tests, and I will choose not to do the updated in this version.

But in version 2.0.0 this are fixed.

**Comment by tearhear18** [comment]
@mauroreisvieira what i did on my project is really write your implementation on my source code. since  i modified a lot in css and extra feature in calendar

**Comment by tearhear18** [comment]
@mauroreisvieira 
<img width="1021" alt="screenshot 2018-12-11 at 1 05 11 am" src="https://user-images.githubusercontent.com/4946755/49748518-dc146c80-fce0-11e8-89c7-90f42451cadb.png">
<img width="1001" alt="screenshot 2018-12-11 at 1 05 02 am" src="https://user-images.githubusercontent.com/4946755/49748528-e2a2e400-fce0-11e8-8ff8-81ebe4a22b7b.png">

did you intentionally do this? 19 - 31 month of December should be highlighted as part of range going to January 31, 2019

**Comment by mauroreisvieira** [comment]
@tearhear18 no, was not supposed to have this behavior.

**Comment by mauroreisvieira** [comment]
@tearhear18 updated! Thanks for your feedback.
