### ISSUE TITLE
Feature: set already selected dates 

### ISSUE THREAD

**Issue by luckylwk** [maurovieirareis/hello-week#13]
Would be amazing to be able to, like `daysHighlight`, pass an array of already selected dates (using `daysSelected` for example.

I now do it as follows:

```javascript
var cal
cal = new HelloWeek({
    lang: 'en',
    langFolder: '/js/cdn/langs/',
    multiplePick: true,
    disablePastDays: true,
    format: 'YYYY-MM-DD',                   
    nav: ['◀', '▶'],
})
cal.daysSelected = [ (new Date("2019-02-22")).getTime() ]
```

**Comment by mauroreisvieira** [comment]
Hi @luckylwk I go check this.  Thanks for you suggestion.

**Comment by mauroreisvieira** [comment]
Hi again @luckylwk this feature have been added in HelloWeek calendar, in **version 2.1.0**.

[Demo](https://mauroreisvieira.github.io/hello-week/#/docs/demos/selected-days).

Thanks for you suggestion 👍.
