### ISSUE TITLE
Update documention on how to get selected day(s)

### ISSUE THREAD

**Issue by roland-d** [maurovieirareis/hello-week#14]
Hello,

Thank you for this nice lightweight calendar. I am able to make it show up but then I got stuck as I cannot seem to find a way on how to retrieve the selected day / range.

I have looked at issue #8 but this no longer seems to work.

Can you tell me how to get the selected day/range? I was expecting to get it as an argument in my callback but that doesn't seem to be the case.

Once I have this working, I can send a PR to update the documentation on this point. 

Thank you.

**Comment by roland-d** [comment]
I have answered my own question and written the documentation, see PR:
https://github.com/mauroreisvieira/hello-week/pull/15

**Comment by mauroreisvieira** [comment]
Merged. 

@roland-d thanks for you PR.
