### ISSUE TITLE
Function goToDate() results in this.date is undefined.

### ISSUE THREAD

**Issue by roland-d** [maurovieirareis/hello-week#16]
Hello,

When using the `goToDate()` function I always get the JavaScript error:
```js
TypeError: this.date is undefined
````

Steps on how to reproduce:
1. Create a page that loads the calendar JS and markup
2. Open the browser console and execute this code:
```js
const calendar = new HelloWeek({
        range: true
    });
```
3. Verify it works by running `calendar.getDays()`. This should return an array
4. Make the calendar jump to a given day by executing this code:
```js
calendar.goToDate();
```
5. Notice the error
6. Try jumping to a given date by executing this code:
```js
calendar.goToDate('2019-03-01');
```
7. Notice another error
```js
TypeError: this.date.setDate is not a function
```

### Expected result:
Calendar jumps to the given date

### Actual result:
JavaScript error
```js
TypeError: this.date is undefined
````
```js
TypeError: this.date.setDate is not a function
```

### Other info
I might be doing this completely wrong :)

**Comment by mauroreisvieira** [comment]
Hi @roland-d to use this method goToDate() is better to use like this:

```js
    const calendar = new HelloWeek({
        onLoad: () => {
            calendar.goToDate('2019-03-01');
        }
    });
```

But yes, exists on error in HelloWeek, I will go fix during the weekend.

**Demo:**
[Go to Date](https://mauroreisvieira.github.io/hello-week/#/docs/demos/go-to-date)

Thanks again for you feedback 👍

**Comment by roland-d** [comment]
@mauroreisvieira I actually want to use the goToDate() in a different matter. I have 1 calendar used for 2 input boxes. When the user clicks on the inputbox I want to set the calendar to the date set in the inputbox. This is a from and a to date. That is why I am looking at the goToDate() function to forward the calendar.

**Comment by mauroreisvieira** [comment]
@roland-d ok, but I guess your issue is solved, see the demo again.

[Demo Go to Date](https://mauroreisvieira.github.io/hello-week/#/docs/demos/go-to-date)

**Comment by roland-d** [comment]
@mauroreisvieira I see the demo is working but on my own installation I keep getting the error specified in the bug report.

Now I replaced the minified JS file with the one from this repository but now the calendar is completely broken. This is all I get.
![image](https://user-images.githubusercontent.com/359377/53297435-16d96b80-381f-11e9-87e4-f3e1bbfd45a4.png)

**Comment by mauroreisvieira** [comment]
Hi @roland-d can you try update the package again in npm or yarn.

**Comment by roland-d** [comment]
@mauroreisvieira So I build a new file and the jump to is working. Unfortunately, the `selectedDays` option seems broken now as it doesn't highlight the dates set in that.

**Comment by mauroreisvieira** [comment]
You can see the console and . check if everything is ok?

**Comment by roland-d** [comment]
Yes, I checked the console but there is no error.

**Comment by mauroreisvieira** [comment]
Can you send me the example.
