### ISSUE TITLE
Error: You need to specify a selector!

### ISSUE THREAD

**Issue by MasterMind92** [maurovieirareis/hello-week#18]
Hey, here is the error i get : 
**Error: You need to specify a selector!**

But isn't "**.hello-week**" a class selector ?

**Comment by mauroreisvieira** [comment]
Hi man. 
By default the **HelloWeek** use the `.hello-week` class, but if you prefer use a different you need specify on init method.

**example**:

```html
   <div class="myCalendar"</div>
```

```js
new HelloWeek({
    selector: '.myCalendar'
});
```
