### ISSUE TITLE
Enhacement: Disable dates

### ISSUE THREAD

**Issue by fontebasso** [maurovieirareis/hello-week#2]
Is it possible to develop a possibility of passing a list of dates that would like to block?

Example:
```javascript
const myCalendar = new HelloWeek({
    ...
    disableDates: [
        '2018-09-11', '2018-09-13', '2018-09-14'
    ],
    ...
});
```

**Comment by mauroreisvieira** [comment]
Hi @fontebasso yes, its possible, a i have a list of new features and that its one.

**Comment by mauroreisvieira** [comment]
Hi again @fontebasso the version 0.1.0 its available.

Now you can define disable dates and also interval of days.

**eg:**

`disableDates: [
    '2018-04-17', '2018-04-19', '2018-04-23'
],`
`disableDates: [
    ['2018-04-16', '2018-04-24'],
    ['2018-05-16', '2018-05-22']
]`

**Attention**: You only can define dates with this format (YYYY-MM-DD) if you have the `format`option active, in alternative you can use timestamp.

**Comment by fontebasso** [comment]
Awesome, thanks!
