### ISSUE TITLE
Is it possible to add something to get current shown month?

### ISSUE THREAD

**Issue by fabio-craq** [maurovieirareis/hello-week#21]
Hi!
Nice work with this plugin!

Can i ask you if you can add a function that returns the current displayed month and year? 
Or maybe you can suggest me a way to get that data?

thank you!

**Comment by fabio-craq** [comment]
Btw, I've tried with this:
`var month = $('.period').html(); var d = new Date(month);`
But works only with english calendar localization.

thank you!

**Comment by mauroreisvieira** [comment]
Hi @fabio-craq thanks. At the moment is not possible get the current month or year. But I go add the methods.

**Comment by fabio-craq** [comment]
hi @mauroreisvieira   thanks a lot for the answer! 
hope to hear from you soon!

**Comment by mauroreisvieira** [comment]
Hi @fabio-craq check new version.

https://mauroreisvieira.github.io/hello-week/#/docs/demos/get-month-year

**Comment by fabio-craq** [comment]
Thank you @mauroreisvieira!! 
I'll update and give you a feedback asap!

**Comment by mauroreisvieira** [comment]
Thank you, to use Hello Week.

**Comment by fabio-craq** [comment]
It works like a charm, thank you!

**Comment by mauroreisvieira** [comment]
Great! Ty for you feedback.
