### ISSUE TITLE
How to import in angular project ?

### ISSUE THREAD

**Issue by Taekick** [maurovieirareis/hello-week#22]
Hello, 

I would like to import hello-week on my angular project.

I installed thanks to npm install... and after i tried to import hello-week 
 'import * as helloWeek from 'hello-week' (like to import "moment.js")  but it doesn't work.

Can you help me please ?

Regards

**Comment by mauroreisvieira** [comment]
Hi @Taekick I will check what is the problem. 

Ty for your report.

**Comment by rcdd** [comment]
Hi @Taekick, you need to import like

`import { HelloWeek } from 'hello-week/src/scripts/hello-week';
`

and in constructor() or onInit() or ngAfterViewInit() you need to create a new instance and send it the options has you want.

**Options object example**

`
this.helloWeekOptions = {
			selector: '#' + this._datePicker.id,
			langFolder: 'assets/langs/',
			weekStart: 1,
			format: 'YYYY-MM-DD',
			onLoad: () => { /** callback function */
			},
			onNavigation: () => { /** callback function */
			},
			onSelect: () => {/** callback function */},
			onClear: () => { /** callback function */
			},
		};
`


**Creating new instance with previous options object**

`
this.helloWeekPicker = new HelloWeek(this.helloWeekOptions);
`



I hope this help you.

**Comment by francescobaldan** [comment]
@rcdd I still got errors
```javascript
ERROR Error: Uncaught (in promise): TypeError: hello_week_src_scripts_hello_week__WEBPACK_IMPORTED_MODULE_2__.HelloWeek is not a constructor
TypeError: hello_week_src_scripts_hello_week__WEBPACK_IMPORTED_MODULE_2__.HelloWeek is not a constructor
    at new TodayComponent (today.component.ts:19)
    at createClass (core.js:22148)
    at createDirectiveInstance (core.js:22029)
    at createViewNodes (core.js:23255)
    at createRootView (core.js:23169)
    at callWithDebugContext (core.js:24177)
    at Object.debugCreateRootView [as createRootView] (core.js:23687)
```

This is my component .ts file

```typescript
import { Component, OnInit } from '@angular/core';
import { HelloWeek } from 'hello-week/src/scripts/hello-week';

@Component({
  selector: 'app-today',
  templateUrl: './today.component.html',
  styleUrls: ['./today.component.styl']
})
export class TodayComponent implements OnInit {

  calendar: HelloWeek

  calendarOptions = {
    selector: '#calendar'
  }

  constructor() {
    this.calendar = new HelloWeek(this.calendarOptions)
  }

  ngOnInit() {
  }

}

```

**Comment by rcdd** [comment]
@Taekick 
1 - Do you have the last version? Which version you have?
2 - Are you using webpack?

Another thing is, probably is better create instance in ngAfterViewInit() method because the calendar will search for an element that could't be created yet if you call in constructor().

**Comment by Taekick** [comment]
Hi all, 
after digging, I was able to use the plugin.

`import 'hello-week/dist/hello.week.min.js';`
`datepicker: any;`
`this.datepicker = new window['HelloWeek']();`

**Comment by francescobaldan** [comment]
> Hi all,
> after digging, I was able to use the plugin.
> 
> `import 'hello-week/dist/hello.week.min.js';`
> `datepicker: any;`
> `this.datepicker = new window['HelloWeek']();`

@Taekick I still have errors with this, because HelloWeek can't find the lang files. With your code `this.datepicker = new window['HelloWeek']();` it searches on `http://localhost:4200/dist/langs/en.json`, which is obviously a wrong path

**Comment by rcdd** [comment]
@francescobaldan
Please try copy lang folder from 'Hello-Week' node_modules folder and paste in project assets folder. It can fix you issue.

Let me know if you works!

**Comment by francescobaldan** [comment]
@rcdd thank you so much! It worked copying the `lang` folder on the `assets` folder and setting that folder on options. This is the code I use to initialize HelloWeek:

```typescript
ngOnInit() {
  this.helloWeekPicker = new window['HelloWeek']({
    langFolder: './assets/langs/'
  })
}
```

**Comment by mauroreisvieira** [comment]
TY @rcdd to help me in this answer.
