### ISSUE TITLE
daysHighlight and setDaysHighlight BUG

### ISSUE THREAD

**Issue by fabio-craq** [maurovieirareis/hello-week#24]
Hi,
the 2.10.1 broken the daysHighlight parameter and the setDaysHighlight function.

need fix ASAP!! 

Thank you.

_Originally posted by @fabio-craq in https://github.com/mauroreisvieira/hello-week/issues/23#issuecomment-492179084_

**Comment by mauroreisvieira** [comment]
reopen the issue [23](https://github.com/mauroreisvieira/hello-week/issues/23).
