### ISSUE TITLE
Simplified Chinese translation

### ISSUE THREAD

**Issue by aiyogit** [maurovieirareis/hello-week#25]
`{
    "days": [
        "星期天",
        "星期一",
        "星期二",
        "星期三",
        "星期四",
        "星期五",
        "星期六"
    ],
    "daysShort": [
        "周日",
        "周一",
        "周二",
        "周三",
        "周四",
        "周五",
        "周六"
    ],
    "months": [
        "一月",
        "二月",
        "三月",
        "四月",
        "五月",
        "六月",
        "七月",
        "八月",
        "九月",
        "十月",
        "十一月",
        "十二月"
    ],
    "monthsShort": [
        "一月",
        "二月",
        "三月",
        "四月",
        "五月",
        "六月",
        "七月",
        "八月",
        "九月",
        "十月",
        "十一月",
        "十二月"
    ],
    "today": "今天",
    "clear": "清空"
}
`

**Comment by mauroreisvieira** [comment]
Hi @aiyogit thanks for your suggestion.
