### ISSUE TITLE
todayDate timezone issue

### ISSUE THREAD

**Issue by yodaXX** [maurovieirareis/hello-week#26]
Hi,
found hello week through a listing site.
i tested hello week and ran into issues at highlighting todays date.
In this demo the highlight is working: https://www.cssscript.com/demo/minimal-clean-inline-date-picker-hello-week/ dont know what version they are using.
Did a bit of research into the code and saw that this.todayDate timestamp has a -2 Hour offset compared to todays date in this.days. My Timezone is GMT +2.
As a Hotfix i added the offset to this.todayDate
```
this.todayDate=a.Utilities.setToTimestamp()-(new Date().getTimezoneOffset() * 1000  * 60)
```
It seems to work, do u see any issues with my solution?

**Comment by mauroreisvieira** [comment]
Hi @yodaXX I don't know what version the CSSScript use for this demo. 

But please check if everything its ok in Oficial website:
https://mauroreisvieira.github.io/hello-week/#/docs/demos/highlight-dates

**Comment by yodaXX** [comment]
The Fix i applied, was for the latest state of the git repository.
In my case the todayHighlight isnt working for the demos.

**Comment by mauroreisvieira** [comment]
Hi @yodaXX  check new version.

[2.10.3](https://github.com/mauroreisvieira/hello-week/releases/tag/2.10.3)
