### ISSUE TITLE
Feature request: Max selectable

### ISSUE THREAD

**Issue by luckylwk** [maurovieirareis/hello-week#28]
We want to only allow a user to select a maximum of 5 days.

Any suggestions on how to achieve this with the current setup? I tried overwriting `this.selectedDates` in the `onSelect` callback, but then the CSS doesn't update and the divs don't have an identifier by date to remove any `is-selected` classes.

**Comment by mauroreisvieira** [comment]
Hi @luckylwk it's a god feature.

I'm working on a new core for Hello week.

For now you can go with:

```
var calendar = new HelloWeek({
    multiplePick: true,
    onSelect: () =>
    {
        if (calendar.getDays().length > 5) {
            calendar.daysSelected.pop();
        }
    }
});
```

**Comment by luckylwk** [comment]
That does not work as it keeps updating the UI by adding the classes. It works for the data, but not for the UI

**Comment by mauroreisvieira** [comment]
Inside validation call `calendar.update()` will update you calendar.

**Comment by luckylwk** [comment]
That worked. Thanks Mauro!

Looking forward to using the new version once its ready 😄

**Comment by mauroreisvieira** [comment]
TY @luckylwk for use Hello Week.

Like I said, I'm working in new Hello Week core. In version 3, this options it's available.
