### ISSUE TITLE
Bug in range selection

### ISSUE THREAD

**Issue by bauermar** [maurovieirareis/hello-week#29]
Hello,

I think your calendar plugin is very nice, but I found an error. On choose range and disablePastDays the rang is only working on next month days. I using a Chrome on Mac with lastest version.

**Comment by mauroreisvieira** [comment]
Hi @bauermar I will check this. 

TY for your feedback.

**Comment by mauroreisvieira** [comment]
Hi @bauermar check new version.

[2.10.3](https://github.com/mauroreisvieira/hello-week/releases/tag/2.10.3)
