### ISSUE TITLE
find demo

### ISSUE THREAD

**Issue by andresog14** [maurovieirareis/hello-week#31]
Hi Mauro,

can you help me please? where I can find this exactly demo https://www.borahvandoorslaer.be/node_modules/hello-week/demos/demos.html

**Comment by mauroreisvieira** [comment]
Hi @andresog14

I don't have more this example, but what do you need, toggle to range or button today?

**Comment by andresog14** [comment]
Hi Mauro,
actually yes, I need the toogle to range, can you help me please?

**Comment by mauroreisvieira** [comment]
It's simple.

**For example:**

```js
const calendar = new HelloWeek();
calendar.setRange(true);
```

**Comment by andresog14** [comment]
Thanks for your help Mauro!
