### ISSUE TITLE
Disable dates From DB

### ISSUE THREAD

**Issue by andresog14** [maurovieirareis/hello-week#32]
Hi Mauro,

Can you help me pls?

how can I disable dates from a BD, I got a DB with dates that insert in the table, but how can I use those days and disable it? I am using ajax and puting function at the disableDates. This is my code

    function mostrar() {
            var xhr = new XMLHttpRequest();
            var x = document.querySelectorAll('.hello-week__day')
            

            xhr.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    //Al hacer parse de un array recibimos un array
                   var alumnos = JSON.parse(this.responseText);
                    //Recorremos el array
                    for (var i = 0; i < alumnos.length; i++) {

                       console.log(alumnos[i]);  
                    } 
                    
                   var cadena = JSON.stringify(alumnos);

                   return cadena;
                    
                  }
                                       
                }
                xhr.open("GET", "array2.php", true);
            xhr.send();
            }

**Comment by mauroreisvieira** [comment]
Hello.
You can initialize the Hello Week after you receive the dates.

**Comment by andresog14** [comment]
can you give me and example pls? Im new in JS so I really don't understand what you say

**Comment by mauroreisvieira** [comment]
Yes, sure I will create example ASAP.

**Comment by andresog14** [comment]
I appreciate your help, thank you so much

**Comment by mauroreisvieira** [comment]
Hi again @andresog14 check this example:

https://jsfiddle.net/mauroreisvieira/6fh97xaL/4/

Things you need to keep in mind:

```js
const calendar = new HelloWeek({
  selector: ".calendar",
  langFolder: "https://cdn.jsdelivr.net/npm/hello-week@2.10.3/dist/langs/en.json",
  disableDates: [] // 1º it's required start with the empty array
});
```

```js
// 2º format format required YYYY-MM-DD
birthdays.push(`${year}-${month.toString().padStart(2, '0')}-${day.toString().padStart(2, '0')}`);
```

```js
// 3º update HTML
calendar.update();
```

**Comment by andresog14** [comment]
thank you so much Mauro, Im going try to put this code in the calendare, I will tell you if it works.
