### ISSUE TITLE
display of days problem

### ISSUE THREAD

**Issue by vincentdurufle** [maurovieirareis/hello-week#33]
Hey great stuff !
Just for the record i had a problem with the display of days not working properly. There were only 5 days being displayed in a line. 
The problem was in the .day class styling the padding with 1em on all sides. Got it working by removing the left and right padding.

I don't know if I'm the only one but thought i'd send some feedback !

**Comment by mauroreisvieira** [comment]
Hi vincentdurufle do you import all css files? I guess is something related with box-sizing

**Comment by vincentdurufle** [comment]
Yeah i imported everything. Thought it was some kind of problem with my own css causing issues with it but even when i removed my styling the problem was still there.

**Comment by mauroreisvieira** [comment]
@vincentdurufle TY for your report, have you add box-sizing: border-box; in your CSS right?

If yes, please can you provide some screenshots to see?

TY!
