### ISSUE TITLE
How to use this module with Angular/Ionic Project?

### ISSUE THREAD

**Issue by hnguyen48206** [maurovieirareis/hello-week#41]
Hi,

I'm trying to integrate this module into my mobile (ionic) project using this command to install **npm install hello-week --D** and then import it with **import * as HelloWeek from 'hello-week'**
However, the editor keeps saying 'Cannot find module 'hello-week''. Is there any way to properly use this calendar with angular? Any help would be much appreciated.

Best Regards.

**Comment by mauroreisvieira** [comment]
Hi @hnguyen48206 it's probably required to declare the module to use that. 

But try to install `npm i 3.0.4-alpha -D` and check if the issue persists.
