### ISSUE TITLE
getDays() values are two days out on BrowserStack's Windows 8.1 machines ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by theodorewilkins** [maurovieirareis/hello-week#47]
Its not clear if this is an issue with browerstack or hello-week but the getDays function generates dates two days before the date selected on Windows 8.1 browerstack machines (across all major browser brands). I don't have access to another instance of Windows 8.1 to confirm if this is an issue with browerstack or hello-week. Is this a known issue? And are there any suggestions re. how to resolve this? 

![Screenshot 2020-07-21 at 17 08 51](https://user-images.githubusercontent.com/35626619/88082122-43f78e00-cb79-11ea-955b-ed4f06afa54f.png)

**Comment by mauroreisvieira** [comment]
Hello @theodorewilkins thanks for your report. I will check ASAP, but can you check the version 3.x if the issue exists?

Thanks again.

**Comment by jdtig** [comment]
I had this same problem on Windows 11 with hello-week 2.10.3.

If I run 3.0.4-beta and use the getDaySelected() function it does appear to be fixed.

**Comment by mauroreisvieira** [comment]
Hey @jdtig can you give me more information.

What is your time zone?
Can you share some videos or screenshots? 

I would like to help you, but I need to reproduce the issue on my side.

TY

**Comment by jdtig** [comment]
I'm in US CST (Chicago). Windows 11, Chrome v.97.

Here's what it looks like when I click on Jan 14: 
![error02](https://user-images.githubusercontent.com/88938203/149379885-76b7ee21-897b-4a29-bbe6-27815992f546.png)


If I remove the Bootstrap CSS, I get some other weirdness and dates aren't lining up.
![error01](https://user-images.githubusercontent.com/88938203/149379749-cfd3f5f2-58a7-465b-93bc-8d62c85ff06e.png)


Here's the HTML I'm using:

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/hello-week@2.10.3/dist/css/hello.week.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/hello-week@2.10.3/dist/css/hello.week.theme.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <div class="hello-week">
      <div class="navigation">
        <button class="prev">Prev</button>
        <div class="period"></div>
        <button class="next">Next</button>
      </div>
      <div class="week"></div>
      <div class="month"></div>
    </div>

<script src="https://cdn.jsdelivr.net/npm/hello-week@2.10.3/dist/hello.week.min.js"></script>
<script>
  const calendar = new HelloWeek({
      langFolder: "/static/js/",
      onSelect: () => {
          console.log(calendar.getDays());
      },
  });
</script>

</body>
</html>
```

**Comment by jdtig** [comment]
And yes, it does seem to be related to time zones. If I change my time zone in Windows to UTC, it seems to select the correct day.

**Comment by mauroreisvieira** [comment]
Hey @jdtig can you please test version **2.12.0-rc**

**Check demo:**
https://jsfiddle.net/rq2x3gka/2/

**Comment by jdtig** [comment]
Hi Mauro,

It looks like it's selecting the correct day when I use 2.12.0.

Thanks you so much!
