### ISSUE TITLE
Issue after modifying the DOM

### ISSUE THREAD

**Issue by leobenkel** [maurovieirareis/hello-week#51]
Hello,

I am working on a project where I kind of want to color the dates , similarly to what Github does on the profile page with the days colored.

I use jquery to select the `.day` element and modify the content of the one that have activities.

However, those days now stop working when clicked on, with the following error:

```
hello.week.min.js:1 Uncaught TypeError: Cannot read property 'locked' of undefined
    at HTMLDivElement.<anonymous> (hello.week.min.js:1)
```

It is minified which makes it hard to find out exactly where it comes from, but I supposed it is somewhere around here ? https://github.com/mauroreisvieira/hello-week/blob/0ebb7255f057f4d31218d0402c1ab32965dfe259/src/core/calendar.ts#L309-L343 ?

**Comment by mauroreisvieira** [comment]
Hi @leobenkel can you share a snippet how do you are initialise HelloWeek?

Also you can customize color of highlight dates, that way: https://hello-week.now.sh/#/docs/v2/highlight-dates

**Comment by leobenkel** [comment]
Here is how I initialize the calendar. I am using `requirejs` 

```javascript
   let calendar = new calendarLib({
                selector: '.calendar-container',
                lang: 'en',
                langFolder: '/config/calendar/langs/',
                format: 'YYYY-MM-DD',
                defaultDate: null,
                todayHighlight: true,
                weekStart: 1,
                monthShort: false,
                weekShort: true,
                minDate: null,
                maxDate: today,
                daysSelected: null,
                daysHighlight: null,
                multiplePick: false,
                disableDaysOfWeek: null,
                disableDates: null,
                disablePastDays: false,
                range: false,
                locked: false,
                rtl: false,
                nav: ['◀', '▶'],
                timezoneOffset: new Date().getTimezoneOffset(),
                onLoad: function () {
                    $('.calendar-action-today').click(function () {
                        return calendar.goToDate(date.todayDashSeparated());
                    });

                    setupMonth(this);
                },
                onNavigation: function () {
                    setupMonth(this);
                },
                onSelect: function () {
                    let dateSelected = dateUtil.reduceDate(this.daysSelected[0]);

                    let findDataForDate = _.find(data, function (d) {
                        return d.data.date == dateSelected;
                    });

                    if (findDataForDate) {
                        renderEvents([findDataForDate]);
                    } else {
                        renderEvents(data);
                    }
                },
                beforeLoad: function () { },
                beforeCreateDay: function (data) { }
            });
```

**Comment by leobenkel** [comment]
Thank you for your suggestion but I need to have something richer than just one color.

**Comment by mauroreisvieira** [comment]
Ok, you are using version 3.0.0 (beta) right? 
So, what do you want is customize color of dates. Do you have an array with dates that you want customize?

**Comment by leobenkel** [comment]
I got the latest from the [Release](https://github.com/mauroreisvieira/hello-week/releases) which is `2.10.3`.

I have an array of date with an array of color, and I need to add blocks for all those colors inside each of the date. Something like this:

<img width="1043" alt="Screen Shot 2020-11-25 at 17 37 09" src="https://user-images.githubusercontent.com/4960573/100256250-6ddf0980-2ef9-11eb-98e6-697a9623cdc2.png">

**Comment by mauroreisvieira** [comment]
In that case, you are using options that are not available in that version (2.10.3).

For example: `beforeLoad` or `beforeCreateDay`.

So version **2.x don't allow an option to customize DOM**, that option is only available on version 3.

So I give an example of what you can do with version 3.0:

```js
import HelloWeek, { el } from 'https://cdn.jsdelivr.net/npm/hello-week@3.0.4-beta/dist/hello.week.min.esm.js';

const days = [
    {
        date: '2020-11-20',
        style: { color: '#fff', backgroundColor: '#F44336' },
    },
    {
        date: '2020-11-21',
        style: { color: '#fff', backgroundColor: '#9C27B0' },
    },
    {
        date: '2020-11-22',
        style: { color: '#fff', backgroundColor: '#673AB7' },
    },
    {
        date: '2020-11-23',
        style: { color: '#fff', backgroundColor: '#2196F3' },
    },
    {
        date: '2020-11-24',
        style: { color: '#fff', backgroundColor: '#009688' },
    },
];

const customizeDate = (date) => days.find((day) => day.date === date) || {};

new HelloWeek({
    selector: '.calendar',
    format: 'YYYY-MM-DD',
    defaultDate: null,
    todayHighlight: true,
    weekStart: 1,
    monthShort: false,
    weekShort: true,
    minDate: null,
    maxDate: new Date(),
    daysSelected: null,
    daysHighlight: null,
    multiplePick: false,
    disableDaysOfWeek: null,
    disableDates: null,
    disablePastDays: false,
    range: false,
    locked: false,
    rtl: false,
    nav: ['◀', '▶'],
    timezoneOffset: new Date().getTimezoneOffset(),
    beforeCreateDay: (data) => {
        const { date } = data;
        const { style } = customizeDate(date);

        return {
            ...data,
            ...{
                node: el(
                    'div',
                    data.node.attributes,
                    el(
                        'span',
                        { class: ['day-color'], style },
                        data.day.toString()
                    )
                ),
            },
        };
    },
});
```

As you can see on that snippet it's possible manipulate **day node** before rendering using `beforeCreateDay`. 

Also using `el` allow a possibility to customize everything on node element, like add styles or an array of class as adding other different attributes.

Look that exemple working: https://jsfiddle.net/x5d724gy/4/

**Comment by leobenkel** [comment]
ok, i am trying to load the v3 but for some reason `requireJS` is not happy about it. works perfectly with v2.x that i was using tho.

**Comment by mauroreisvieira** [comment]
Ok, version 3 it's available in `cjs`, `iife` (default) and `esm`.

but for you understand what is the problem with that error:

```
hello.week.min.js:1 Uncaught TypeError: Cannot read property 'locked' of undefined
    at HTMLDivElement.<anonymous> (hello.week.min.js:1)
```

What I understand from you explanation you are adding a new HTMLElement inside the HTMLElement with class `day`. 
The problem is that you are adding a new element but that element will preventing the click on HTMLElement with class `day`.
To fixed that you should add `pointer-events: none` in element that you are adding inside HTMLElement with class `day`.

```html
<div class="hello-week">
  ....
    <div class="day">
        24
        <span style="pointer-events: none"><!-- that will contain color --></span>
    <div>
</div>
```

**Comment by leobenkel** [comment]
ok , I made some progress. I was able to add the library to `RequireJS` , using 

```
 paths: {
        ...other libraries...
        calendarLib: [
            '//cdn.jsdelivr.net/npm/hello-week@3.0.4-beta/dist/hello.week.min'
        ]
},
shim: {
        calendarLib: {
            exports: 'HelloWeek'
        }
}
```

I am able to render the calendar, using your example and what i have previously done. 

Right now, I am having trouble understanding how to get/use your `el` magic thing :)

**Comment by leobenkel** [comment]
What I am doing right now:

```javascript
beforeCreateDay: function (input) {
    // ... more code ...
    let container = // ... build all the colors ...

    let dayContent = $(`<div></div>`);
    dayContent.append(container);
    dayContent.append(`<div class="day-number">${input.day}</div>`);
    dayContent.addClass('day-with-activities');
    input['node'] = dayContent.el;

    return input;
}
```

but i am getting:

```
Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at T (hello.week.min.js:1)
    at X.createDay (hello.week.min.js:1)
    at X.createMonth (hello.week.min.js:1)
    at X.mounted (hello.week.min.js:1)
    at X.beforeMount (hello.week.min.js:1)
```

**Comment by mauroreisvieira** [comment]
Good to know that you made progress :)

Ok, so you don't need that:

```js
let dayContent = $(`<div></div>`);
dayContent.append(container);
dayContent.append(`<div class="day-number">${input.day}</div>`);
dayContent.addClass('day-with-activities');
input['node'] = dayContent.el;
```

You can use only `el()` function.

So let me explain how that function works:

```js
function el(nodeName: string, attributes: any, ...args: any) 
````

**nodeName:** Create node element like: p, div, a, ul, li, nav...
**attributes:** Object with attributes, like: id, class, styles....
**args:** Can receive a string our a other `el()`.

Confused??? Ok, let's see an exemple:

If you call that function `el(div, { id: "foo" }, "Hello"); ` will return a virtual node element like that:

```js
{
  nodeName: "div",
  attributes: {
    "id": "foo"
  },
  children: ["Hello!"]
}
```
Back to you code, you can replace your jQuery code for that:

```js
beforeCreateDay: (data) => {
    const container = el(
        'div',
        {},
        el('div', { style: { color: '#f00' } }),
        el('div', { style: { color: '#ff0' } }),
        el('div', { style: { color: '#00f' } }),
        el('div', { style: { color: '#f0f' } })
    );
    return {
        ...data,
        ...{
            node: el(
                'div',
                data.node.attributes,
                el(
                    'div',
                    { class: 'day-with-activities' },
                    el(
                        'div',
                        { class: 'day-number' },
                        container,
                        data.day.toString()
                    )
                )
            ),
        },
    };
},
```

**HTML results:**

```html
<div class="day">
   <div class="day-with-activities">
      <div class="day-number">
         <div>
            <div style="color: #f00;"></div>
            <div style="color: #ff0;"></div>
            <div style="color: #00f;"></div>
            <div style="color: #f0f;"></div>
         </div>
         25
      </div>
   </div>
</div>
```

**Comment by leobenkel** [comment]
Thank you for your explanation ! 
I understand how to use `el()` but I dont understand how to bring into my code using `RequireJS`. 

the file where i use `HelloWeek` looks like:

```javascript
define([
    // ...lot more...
    'jquery',
    'calendarLib',
],
    function (/* ...lot more... */, $, calendarLibl) {
        let startHelloWeek = function(selector) {
             let calendar = new calendarLib({
                 selector: selector,
                 // ...the other thing we discussed above...
                 beforeCreateDay: function(input) {
                    // the code I copied above with Jquery DOM
                 }
            });
       }    
});
```
`calendarLib` come from https://github.com/mauroreisvieira/hello-week/issues/51#issuecomment-733873381

If I try to use `el` it does not exist.

```
Uncaught ReferenceError: el is not defined
```

**Comment by mauroreisvieira** [comment]
I never work in RequireJS.

But try to use that way: `calendarLib.el()`

Any way why do you need `RequireJS`?

**Comment by leobenkel** [comment]
I am building a client side only app and requirejs is the only way i know how to do it without the need to use any construction CI/CD pipeline. 

I found a way to make it work. 

I downloaded the release js locally. 

And wrapped it into a `define` , it works now :) 

It is an open source app , I will send you the link when it is all working out

**Comment by mauroreisvieira** [comment]
Ok, I happy to see that working. 

I will waiting for for that link. 👍

and thanks for choose Hello Week.

**Comment by leobenkel** [comment]
I found why it does not work, it is at https://github.com/mauroreisvieira/hello-week/blob/0ebb7255f057f4d31218d0402c1ab32965dfe259/src/util/index-of.ts#L5

The array is containing the original days DOM created. But the target is what has been clicked on which might not be the right thing. 

I now understand what you meant by `pointer-events: none` !

**Comment by mauroreisvieira** [comment]
Yea, I will fix that to avoid that kind of workarounds.

**Comment by leobenkel** [comment]
@mauroreisvieira , just for you: https://daily-achievements.netlify.app/ , it is a WIP. It is not public yet. But this is where I use the library :)
