### ISSUE TITLE
`this.date.setDate` is not a function

### ISSUE THREAD

**Issue by effone** [maurovieirareis/hello-week#53]
If I call `calendar.goToday();` I am getting this:

![image](https://user-images.githubusercontent.com/21265591/106368973-c3111e80-6373-11eb-94f9-06aa27603ccf.png)

What am I doing wrong?

Edit:
Managing this way by the time I get help:
```js

var d = new Date();
calendar.goToDate(d.getFullYear() + "-" + pad((d.getMonth()+1),2) + "-" + pad(d.getDate(),2));
```
and the padding:
```js
function pad (str, max) {
	str = str.toString();
	return str.length < max ? pad("0" + str, max) : str;
}
```

**Comment by mauroreisvieira** [comment]
Hi @effone sorry it's a mistake on Hello Week docs. 

`goToday()` method is not more supported, now you should use `goToDate()`, and by default if you don't pass any values in `goToDate` will jump to today date.

So you can change your approach to:

```js
calendar.goToDate();
```

**Comment by effone** [comment]
Thanks for the help.
