### ISSUE TITLE
Wrong date in getDays

### ISSUE THREAD

**Issue by Jako** [maurovieirareis/hello-week#65]
hello-week.js seems to have an issue with getDays after a daylight saving date. Please take a look at https://jsfiddle.net/treehillstudio/jq75fv8d/14/ select October 30th and look into the browser console. Every day after October 30th retrieves -2 days in getDays. Is this a known issue? How can this be solved? I am using 2.14.2 there.

**Comment by mauroreisvieira** [comment]
Hey @Jako I will take a look ASAP, thanks for the report.

**Comment by mauroreisvieira** [comment]
Hey @Jako can you please test version 2.14.3, let me know if everything works as expected.

**Comment by Jako** [comment]
Can you add a dist folder in the fix/65-wrong-date-in-getdays branch?

**Comment by mauroreisvieira** [comment]
Not sure if I understand, the dist folder is ignored, do you want?

**Comment by Jako** [comment]
The easiest way to check the script would be a dist folder. Then I don't have to build it locally. But maybe I can import the branch in the package.json of the website package.

**Comment by mauroreisvieira** [comment]
You can check the files on NPM: https://www.npmjs.com/package/hello-week?activeTab=code

**Comment by Jako** [comment]
Everything works fine, thanks for the quick fix. I did not notice a new release tag here. So I did not realised the new version on npm.
