### ISSUE TITLE
Easy way to get selected date formatted?

### ISSUE THREAD

**Issue by IP-Developer** [maurovieirareis/hello-week#8]
I need to get the selected date formatted in the `onSelect` callback. Any easy way to do this?

**Comment by 8geonirt** [comment]
@WrongWay You can easily do that by setting the desired format in the `HelloWeek` `format` option.

For example I'm using the `YYYY-MM-DD` below
```
var yourCalendar = new window.HelloWeek({
      format: 'YYYY-MM-DD',
      selector: '.calendar',
      onChange: function() {
        var selectedDate = this.selectedDays[0];
        //Do whatever with your selected date
      }
    });
```

By using that format you can easily see the selected dates in the HelloWeek array
