### ISSUE TITLE
Disable days

### ISSUE THREAD

**Issue by felipericcetto** [maurovieirareis/hello-week#9]
Hello, I found the project very cool.
I'm just having a hard time using "disableDates". I'm passing the dates, for example:
['2018-10-02', '2018-10-09', '2018-10-16', '2018-10-23']

but the days that are getting disabled are always the day before those.
Is it a problem with daylight saving time?
Thank you

**Comment by mauroreisvieira** [comment]
@felipericcetto thanks for report, I will check this.

**Comment by mauroreisvieira** [comment]
@felipericcetto I have been look to the code and I not find any bug. Can you send me more details about all options are you using.
